### PR TITLE
add listener to TrayMenuController

### PR DESCRIPTION
**Pull request by ledwardchow**
Add listener to support https://github.com/cryptomator/cryptomator/pull/2489

### CODE REVIEW

**Review by overheadhunter — CHANGES_REQUESTED** [review]
Could you add some JavaDoc (just a line or two, explaining what implementers are expected to do with the given listener).

**Comment by ledwardchow** [comment]
> Could you add some JavaDoc (just a line or two, explaining what implementers are expected to do with the given listener).
> 
> Edit: Also I just noticed `onBeforeShow` is a terrible name, as it suggests this has something to do with `showTrayIcon(...)`. I see two options:
> 
> 1. Either set up the listener during `showTrayIcon(...)` (add a new nullable param)
> 2. Or rename this method to `onBeforeOpenMenu(...)`

I've committed changes for option 2).

**Review by overheadhunter — CHANGES_REQUESTED** [review]
Looks good, however can you please undo the xml file, as it is unrelated?

@infeo While I'm fine with this, we should at least discuss whether it is a more consistent API design to set _all_ listeners during `showTrayIcon`. Or whether this mixed approach is acceptable? See [listener A](https://github.com/cryptomator/cryptomator/blob/b8500bf4962d434246d19c2b6f17118748c24644/src/main/java/org/cryptomator/ui/traymenu/AwtTrayMenuController.java#L47) vs [listener B](https://github.com/cryptomator/cryptomator/blob/b8500bf4962d434246d19c2b6f17118748c24644/src/main/java/org/cryptomator/ui/traymenu/AwtTrayMenuController.java#L68).  I leave this up to you, since you will have to live with it for the foreseeable future :wink:

**Comment by ledwardchow** [comment]
> Looks good, however can you please undo the xml file, as it is unrelated?

done!

**Review by overheadhunter — APPROVED** [review]

**Pull request merged**
